name: rick_and_morty
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
  internet_connection_checker_plus: ^2.5.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
